//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineFix.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> RoastLevelID { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public Nullable<int> DrinkwareTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
    
        public virtual DrinkwareType DrinkwareType { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductImage ProductImage { get; set; }
        public virtual RoastLevel RoastLevel { get; set; }
    }
}
